### ISSUE TITLE
Change Profile Name, please?

### ISSUE THREAD

**Issue by schantanu** [shantanu1k/Profile#1]
Hello,

I had originally owned the profile name 'schantanu' on Github, and had to change because of personal reasons, for a month. Can you please choose a different profile name, as I have bought the domain 'schantanu.com' with the same name to host my resume here.

Thanks for understanding.
Let me know if you have any questions.

**Comment by shantanu1k** [comment]
I have changed my username from Schantanu to shantanu1k.


   You're always welcome!!

**Comment by schantanu** [comment]
Thanks a lot, pal. Let me know if you need any help in the future.
